### ISSUE TITLE
‘Scaffold.of() called with a context that does not contain a Scaffold’

### ISSUE THREAD

**Issue by albertms10** [minidosis/flutter_firebase_auth#1]
En `SignInPage`, `Scaffold.of()` se llama haciendo referencia a un contexto que aún no tiene definido el Scaffold.
https://github.com/minidosis/flutter_firebase_auth/blob/1bd7035e83c3031dca5746507e4c41e75ffe5761/lib/login_flow/pages/signin_page.dart#L24-L29

## Archivos afectados
https://github.com/minidosis/flutter_firebase_auth/blob/1bd7035e83c3031dca5746507e4c41e75ffe5761/lib/login_flow/signin_flow_app.dart#L6-L10
https://github.com/minidosis/flutter_firebase_auth/blob/1bd7035e83c3031dca5746507e4c41e75ffe5761/lib/login_flow/pages/signin_page.dart#L54-L65

## Propuesta de cambio
Modificar dónde se crea el Widget `Scaffold`.

En `signin_flow_app.dart`:
```dart
Widget build(BuildContext context) {
  return MaterialApp(
     home: Scaffold(
       body: SignInPage(),
       backgroundColor: Colors.white,
     ),
  );
}
```
En `signin_page.dart`:
```dart
Widget build(BuildContext context) {
  if (_showProgress)
    return Center(child: CircularProgressIndicator());

  final SignInConfig config = Provider.of<SignInConfig>(context);
  final primaryColor = Theme.of(context).primaryColor;

  return SingleChildScrollView( 
    child: Padding( 
```

**Comment by pauek** [comment]
He dejado el Widget SignInPage igual y he extraído el ``body``, que es casi lo mismo.
