### ISSUE TITLE
Añadir método de Firebase `createUserWithEmailAndPassword`

### ISSUE THREAD

**Issue by albertms10** [minidosis/flutter_firebase_auth#2]
Al recibir la respuesta de `SignUpPage`, llamar la función de `FirebaseAuth` `createUserWithEmailAndPassword`:
https://github.com/minidosis/flutter_firebase_auth/blob/1bd7035e83c3031dca5746507e4c41e75ffe5761/lib/login_flow/pages/signin_page.dart#L98-L104

## Propuesta de cambio
Añadir un método privado a la classe `SignInPage` para que se encargue de llamar la función de `FirebaseAuth` correspondiente.

En `signin_page.dart`:
```dart
_createUserWithEmailAndPassword(EmailAndPassword emailAndPassword) async {
  await FirebaseAuth.instance.createUserWithEmailAndPassword(
    email: emailAndPassword.email, password: emailAndPassword.password);
  }
}
```
En `FlatButton` del mismo archivo que inicia el `Navigator.push()`:
https://github.com/minidosis/flutter_firebase_auth/blob/1bd7035e83c3031dca5746507e4c41e75ffe5761/lib/login_flow/pages/signin_page.dart#L95
```dart
onPressed: () async { 
  EmailAndPassword result = 
      await Navigator.of(context).push( 
    MaterialPageRoute(builder: (_) => SignUpPage()), 
  ); 
  _createUserWithEmailAndPassword(result); 
}, 
```

**Comment by pauek** [comment]
Arreglado!
